//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnygaTaranCrypto.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KnygaTaranCrypto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;AES - Advanced encryption standard&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Описание работы AES&lt;/h1&gt;
        ///		&lt;div&gt;
        ///			Алгоритм AES состоит из последовательности операций, выполняемых над промежуточным массивом 4x4 байт, 
        ///			называемым &lt;b&gt;состоянием&lt;/b&gt;, и обозначаемым через S=S&lt;sub&gt;i,j&lt;/sub&gt;. 
        ///			В начале процесса шифрования 16 байтов состояния (128 бит) инициализируются байтами открытого текста p&lt;sub&gt;i&lt;/sub&gt; , 
        ///			сверху дони [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AES {
            get {
                return ResourceManager.GetString("AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;BlowFish - Алгоритм шифрования&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;h1&gt;Описание работы BlowFish&lt;/h1&gt;
        ///		&lt;div&gt;
        ///			Blowfish является сетью Фейштеля, у которой количество итераций равно 16. Длина блока равна 64 битам, 
        ///			ключ может иметь любую длину в пределах 448 бит. Хотя перед началом любого шифрования выполняется сложная
        ///			 фаза инициализации, само шифрование данных выполняется достаточно быстро.
        ///			Алгоритм предназна [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlowFish {
            get {
                return ResourceManager.GetString("BlowFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;CAST-128 - Алгоритм шифрования&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///		&lt;div&gt;
        ///			&lt;h1&gt;Описание работы алгоритма шифрования CAST-128&lt;/h1&gt;
        ///			&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAqkAAAG+CAIAAAA/fwouAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAJ7/SURBVHhe7V09ehs7r9a5a7FT5PEK9K3ATuMqbTqltJt0LtOlccqoS5sqTeIVRCvw4yL2XnJJkJwBfwGSM9JIxhTnOCP+AC9AggTA4X///v1bySMICAKCgCAgCAgCrwaB/3s1nAqjg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CAST {
            get {
                return ResourceManager.GetString("CAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Cipher Block Chaining (CBC) - Режим сцепления блоков шифротекста&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;p&gt;Каждый блок открытого текста (кроме первого) побитово складывается по модулю 2 (операция XOR) с предыдущим результатом шифрования.&lt;/p&gt;
        ///    &lt;p&gt;Сначала так же как и в случае с ECB, первоначальное сообщение разбиваем на блоки, при необходимости дополнив последний до длины n.&lt;/p&gt;
        ///	    &lt;img alt=&quot;&quot; src=&quot;data:image/png;base64 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CBCMode {
            get {
                return ResourceManager.GetString("CBCMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Cipher Feedback (CFB) - Режим обратной связи по шифротексту&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///        &lt;p&gt;Режим обратной связи по шифротексту, режим гаммирования с обратной связью (англ. Cipher Feedback Mode, CFB). Для шифрования следующего блока открытого текста он складывается по модулю 2 с перешифрованным (блочным шифром) результатом шифрования предыдущего блока.&lt;/p&gt;
        ///        &lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0K [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CFBMode {
            get {
                return ResourceManager.GetString("CFBMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Работа с файлами&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;p&gt;Для работы с файлами есть 3 пункта меню:&lt;/p&gt;
        ///		&lt;ol type=&quot;1&quot;&gt;
        ///			&lt;li&gt;Открыть файл&lt;/li&gt;
        ///			&lt;li&gt;Просмотр файла&lt;/li&gt;
        ///			&lt;li&gt;Сохранить в файл&lt;/li&gt;
        ///		&lt;/ol&gt;
        ///		&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAysAAADuCAIAAAC2+A+RAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAIYuSURBVHhe7V0HgBTF0p7b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopeWithFiles {
            get {
                return ResourceManager.GetString("CopeWithFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Дешифрование&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;p&gt;Описанными в пункте &quot;Шифрование&quot; способами устанавливаем шифро-текст и ключ:&lt;/p&gt;
        ///		&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAysAAAIzCAIAAACPxxFJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAP+lSURBVHhe7F0HYFTF1r676SH0Kr3ZkCKg2LHQsaJi+y34bGABngqKFBFEEKxYQEXF9hRRsaI0e0UBGygoWOkd0ut/yszcububZJ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;DES&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;h1&gt;Описание работы алгоритма шифрования DES&lt;/h1&gt;
        ///		&lt;div&gt;
        ///			Самым распространенным и наиболее известным алгоритмом симметричного шифрования является DES 
        ///			(Data Encryption Standard). Алгоритм был разработан в 1977 году, в 1980 году был принят NIST 
        ///			(National Institute of Standards and Technolody США) в качестве стандарта (FIPS PUB 46).
        ///			DES является классической сетью Фе [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DES {
            get {
                return ResourceManager.GetString("DES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-http://W3Chttp://DTD HTML 4.0 Transitionalhttp://EN&quot;&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;Electronic Codebook (ECB) - Режим электронной кодовой книги&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAEsCAYAAABQRZlvAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAW6gAAFuoB5Y5DEAAAAAd0SU1FB9gMEw8cAS/JC2QAACAASURBVHja7N1/fM31///x+9kP5seG0rKzHxitYVtsfs68SUjvSWF+JZXSD0ne/XqHUugHvfXul96930QS+VEqb6a0N2GbX0XGoo38SAyLGGazX6/vHz47X6dtdjY7x3F2u14uLuV1Xuf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ECBMode {
            get {
                return ResourceManager.GetString("ECBMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Шифрование&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;p&gt;После выбора шифра и режима вы увидите следующее окно:&lt;/p&gt;
        ///		&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAygAAAIvCAIAAAAQ5GiqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAALjRSURBVHhe7b0HeBVHmu99nv2+nXGc8ezc2dkd25gcRFBAAYEkcgaRkUhCIucsQIkgCUlESQQJgSREEgKRc07GAYPBYMDY2BNs7PHYnp1xvHdn9rt8b1V1PEGco+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;GOST-28147&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;h1&gt;Описание работы алгоритма шифрования GOST-28147&lt;/h1&gt;
        ///		&lt;div&gt;
        ///			&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA08AAAGxCAIAAAA1WxoNAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAL6USURBVHhe7b1diK1Plxe2z2gSDQEZZ2IwF0HD7hPStOaNipD+3yghaPcJoQXp4Mdw8GZ3HITum4MoBxWm7w6MuzEX6Q1+HBlkplHpRE7vGIx44b9vNOAkPY3v6Y75vMgQ/CImg6Ke1Ofz1MeqqlXPx/78bV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GOST28147 {
            get {
                return ResourceManager.GetString("GOST28147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;IDEA - Алгоритм шифрования&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;h1&gt;Описание работы алгоритма шифрования IDEA&lt;/h1&gt;
        ///		&lt;div&gt;
        ///			&lt;img alt=&quot;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA1UAAAFnCAIAAADBsPQeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAJFwSURBVHhe7V07tuu4cu1xnTl4GloehIfgQLEn4NzByRw7dfrWjRw68wza/AGoPwokJVHSPsF7fSUQqNr12yiC1F9/4w8IAAEgAASAABAAAkDgmxD465uUha5AAAgAASAABIAAEAACf4P/fakT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDEA {
            get {
                return ResourceManager.GetString("IDEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;Изучение алогоритмов&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;p&gt;
        ///		Для изучения алгоритмов выделите нужный вам алгоритм в окне выбора алгоритмов и нажмите
        ///		&quot;Изучить шифр&quot;, для изучения режима выберите соответствующий режим и нажмите &quot;Изучить режим&quot;
        ///		&lt;/p&gt;
        ///		&lt;img alt=&quot;&quot; style=&quot;width: 300px;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgQAAADdCAIAAABLzv0PAAAABGdBTUEAALGPC/xhBQAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Output Feedback (OFB)&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///	    &lt;p&gt;Режим (OFB) обратной связи вывода превращает блочный шифр в синхронный шифрпоток: это генерирует ключевые блоки, которые являются результатом сложения с блоками открытого текста, чтобы получить зашифрованный текст. Так же, как с другими шифрами потока, зеркальное отражение в зашифрованном тексте производит зеркально отраженный бит в открытом тексте в том же са [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OFBMode {
            get {
                return ResourceManager.GetString("OFBMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;Triple DES&lt;/title&gt;
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;h1&gt;Описание работы Triple DES&lt;/h1&gt;
        ///		&lt;div&gt;
        ///			&lt;img alt=&quot;&quot; style=&quot;width: 300px;&quot; src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAARMAAAEFCAYAAADAJgM+AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAABIAAAASABGyWs+AAAACXZwQWcAAAETAAABBQBKUlj6AABUaUlEQVR42u2dd3wc1dWGn5kt2tWuVr13y73ggm3AYONGDTY2YEqC6b2GQAKEkFASktBCJ+SjdxKqTTcd494btiVZVu+9bZuZ748Z2ZK7sVYa2ffNb2Mjydqde8597znnngK9izFADaABr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrippleDES {
            get {
                return ResourceManager.GetString("TrippleDES", resourceCulture);
            }
        }
    }
}
